# Site settings
title: Kristen MacFarlane
email: krismacfarlane@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thanks for checking out my page! Just trying out Jekyll!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: KrisMakesMaps
github_username:  krismacfarlane

# Build settings
markdown: kramdown
